// ============================================================
// boundaryGaps.ts — detect_boundary_gaps tool handler
// Scans for missing offsets, magic numbers, missing onLayout
// v0.4.1: Added mode param (anchors/all) and influence index display
// v0.5.1: Added margin-inventory, gap-validator modes, batch audit,
//   cross-file style resolution, and design token deviation detection
// v0.6.0: Added vein-propagation mode — AST-driven Vein Propagation
//   Engine for 100% accurate component tree analysis
// v0.8.1: Removed dead code paths (margin-inventory, gap-validator)
//   that delegated to removed BoundaryGapDetector methods.
// v0.8.2: All modes now properly filter results via VeinAnalysisService.
//   Removed dead handleStandardDetection and handleVeinPropagation
//   functions in favor of unified handleModeAwareDetection.
// Phase D: Standardized to use shared ToolResponse pattern.
// v1.2.0: Uses AnalysisContext for single-file analysis.
// ============================================================

import * as fs from 'fs';
import * as path from 'path';
import { BoundaryGapDetector } from '../engine/BoundaryGapDetector.js';
import { runVeinAnalysis } from '../engine/services/VeinAnalysisService.js';
import { validateFilePath } from '../utils/validateFilePath.js';
import { success, error, type ToolResponse } from './shared.js';
import type { BoundaryGapReport } from '../domain/types/index.js';
import type { AnalysisContext } from '../domain/types/context.js';

type GapMode = 'all' | 'vein-propagation';


export function handleDetectBoundaryGaps(args: Record<string, unknown>): ToolResponse {
  try {
    const mode = (args.mode as GapMode) ?? 'all';
    const designTokens = args.designTokens as number[] | undefined;
    const recursive = (args.recursive as boolean) ?? false;

    // Validate file existence for single-file modes
    if (!fs.existsSync(args.filePath as string)) {
      throw new Error(`File not found: "${args.filePath}". Please provide a valid file path.`);
    }

    // Check if filePath is a directory (batch audit mode)
    const isDirectory = fs.statSync(args.filePath as string).isDirectory();

    if (isDirectory || recursive) {
      return handleBatchAudit(args.filePath as string, mode, designTokens);
    }

    // Single file mode — validate extension
    validateFilePath(args.filePath as string);

    const ctx: AnalysisContext = { filePath: args.filePath as string };
    if (args.designTokens !== undefined) ctx.designTokens = args.designTokens as number[];
    if (args.mode !== undefined) ctx.mode = args.mode as 'all' | 'vein-propagation';
    if (args.stylesPath !== undefined) ctx.stylesPath = args.stylesPath as string;
    if (args.recursive !== undefined) ctx.recursive = args.recursive as boolean;
    if (args.maxFiles !== undefined) ctx.maxFiles = args.maxFiles as number;
    if (args.maxFileSizeKB !== undefined) ctx.maxFileSizeKB = args.maxFileSizeKB as number;
    if (args.timeoutMs !== undefined) ctx.timeoutMs = args.timeoutMs as number;

    const report = runVeinAnalysis(ctx.filePath, ctx);

    return formatModeAwareOutput(report, ctx.filePath, mode);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return error(`Error detecting boundary gaps: ${message}`);
  }
}

/**
 * v0.8.2: Unified output formatter that respects the requested mode.
 * Uses the mode-aware summary already generated by VeinAnalysisService.convertToReport.
 */
function formatModeAwareOutput(
  report: BoundaryGapReport,
  filePath: string,
  mode: string,
): ToolResponse {
  const lines: string[] = [];
  lines.push(`[BOUNDARY-GAPS] ${filePath}`);

  if (report.gaps.length === 0) {
    lines.push('[CLEAN] No issues detected.');
    lines.push(`[SUMMARY] ${report.summary}`);
    return success(lines.join('\n'));
  }

  for (const gap of report.gaps) {
    const severity = gap.severity.toUpperCase();
    const influence = gap.influenceIndex !== undefined ? ` | Influence: ${gap.influenceIndex}/10` : '';
    lines.push(`[${severity}] ${gap.category} | ${gap.description}${influence}`);
    lines.push(`  Location: ${gap.location}`);
    lines.push(`  Fix: ${gap.suggestion}`);
  }

  lines.push(`[SUMMARY] ${report.summary}`);
  return success(lines.join('\n'));
}

function handleBatchAudit(
  dirPath: string,
  mode: string,
  designTokens?: number[],
): ToolResponse {
  const detector = new BoundaryGapDetector({
    designTokens,
    mode: mode as 'all' | 'vein-propagation',
  });

  const results = detector.batchAudit(dirPath, mode as 'all' | 'vein-propagation');

  const lines: string[] = [];
  lines.push(`[BATCH-AUDIT] ${dirPath} | Mode: ${mode} | Files: ${results.length}`);

  const errorResults = results.filter((r) => r.gapCount === -1);
  const cleanResults = results.filter((r) => r.gapCount === 0);
  const flaggedResults = results.filter((r) => r.gapCount > 0);

  if (flaggedResults.length > 0) {
    lines.push(`[FLAGGED] ${flaggedResults.length} files with issues:`);
    for (const result of flaggedResults) {
      lines.push(`  ${result.file} — ${result.summary}`);
    }
  }

  if (cleanResults.length > 0) {
    lines.push(`[CLEAN] ${cleanResults.length} files`);
  }

  if (errorResults.length > 0) {
    lines.push(`[ERRORS] ${errorResults.length} files:`);
    for (const result of errorResults) {
      lines.push(`  ${result.file} — ${result.summary}`);
    }
  }

  const totalIssues = flaggedResults.reduce((sum, r) => sum + r.gapCount, 0);
  lines.push(`[SUMMARY] ${flaggedResults.length}/${results.length} files have issues (${totalIssues} total gaps)`);

  return success(lines.join('\n'));
}
